### ISSUE TITLE
Support for Hades?

### ISSUE THREAD

**Issue by randalthor17** [LeadRDRK/wine-rpc-app-list#1]
Executable name: Hades.exe (case sensitive)
App name: Hades
Icon: ![Hades](https://user-images.githubusercontent.com/83530912/211554685-04cdc8f3-bfb1-4ac4-8a32-f7c9cbe88432.png)

**Comment by LeadRDRK** [comment]
Added. Please update your app list.

**Comment by randalthor17** [comment]
Thanks!
